services:
  mysql:
    image: mysql:8.0
    container_name: forex_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: forex_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: forex_user
      MYSQL_PASSWORD: forex_password
      MYSQL_ROOT_HOST: "%"
    command: >
      --default-authentication-plugin=mysql_native_password
      --skip-ssl
      --skip-name-resolve
      --bind-address=0.0.0.0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - forex_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: forex_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - forex_network

  backend_migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: forex_migrate
    environment:
      APP_NAME: ForexApp
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: forex_db
      DB_USERNAME: forex_user
      DB_PASSWORD: forex_password
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    networks:
      - forex_network
    command: >
      bash -c "
        while ! php artisan tinker --execute='DB::connection()->getPdo();' 2>/dev/null; do
          echo 'Waiting for database...'
          sleep 5
        done
        php artisan migrate:fresh --seed --force
      "
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: forex_backend
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      APP_NAME: ForexApp
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: forex_db
      DB_USERNAME: forex_user
      DB_PASSWORD: forex_password
    depends_on:
      - mysql
      - backend_migrate
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    networks:
      - forex_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: forex_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - forex_network

volumes:
  mysql_data:

networks:
  forex_network:
    driver: bridge
